# fly.toml app configuration file generated for the-reel-download-bot on 2023-06-18T13:49:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "the-reel-download-bot"
primary_region = "iad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
